name: chewie_example
description: An example of how to use the chewie for Flutter
version: 1.0.10
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  chewie:
    path: ../
  auto_orientation: ^2.0.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

