name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.7
homepage: https://github.com/brianegan/chewie
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  video_player:
    path: /Users/cnting/Documents/workspace_flutter/video_player
#    git:
#      url: https://github.com/uquabc/video_player.git
#      ref: 'null-safety'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
